# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 46e147dc109bf66b783b05b3dc43e1db00037bf2a7ac12f6582429e433d2caa79881f7e538de5d96830d37bbe19c153f02703b97759793e8889f7322791fc518

test:
  secret_key_base: 62a918257e56f4fe2f757d118b8bebbd0a828093cc2101901efbd6890f49b8bbed5874e4c8a242e9d7e964d06739ec8faf5a49ffb927a69a50c6badd4a4d4343

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
